In [1]:
import pandas as pd
df=pd.read_csv(r"titanic.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [1]:
import numpy as np
np.random.randint(18,21,(300))

array([19, 20, 19, 18, 20, 18, 20, 19, 19, 18, 18, 19, 18, 19, 19, 20, 20,
       18, 18, 19, 18, 19, 18, 20, 19, 19, 19, 18, 19, 18, 18, 20, 20, 18,
       19, 20, 19, 19, 20, 20, 18, 20, 19, 20, 20, 19, 18, 20, 18, 19, 18,
       20, 19, 18, 20, 18, 19, 18, 20, 19, 20, 18, 18, 18, 18, 19, 20, 18,
       20, 20, 19, 20, 20, 19, 20, 20, 18, 20, 20, 20, 19, 19, 18, 18, 18,
       20, 18, 19, 19, 20, 18, 19, 19, 20, 19, 18, 19, 19, 18, 19, 20, 20,
       19, 20, 19, 18, 20, 20, 19, 20, 18, 20, 19, 18, 18, 19, 19, 19, 20,
       18, 20, 18, 19, 18, 18, 19, 20, 20, 20, 20, 20, 19, 19, 20, 20, 20,
       18, 18, 19, 18, 20, 18, 19, 20, 20, 18, 18, 20, 20, 19, 18, 19, 20,
       18, 20, 19, 19, 20, 20, 18, 19, 19, 18, 20, 18, 20, 20, 20, 18, 20,
       18, 19, 19, 18, 19, 19, 18, 20, 20, 19, 20, 19, 18, 18, 20, 20, 20,
       19, 19, 20, 20, 20, 20, 19, 18, 20, 18, 20, 18, 19, 19, 18, 18, 20,
       20, 20, 19, 18, 18, 20, 18, 20, 18, 18, 19, 18, 18, 20, 18, 18, 18,
       18, 18, 20, 18, 19

In [2]:
np.random.seed(400)
arr=np.random.randint(20,99,(6,7))

In [3]:
arr

array([[82, 77, 32, 43, 26, 28, 83],
       [90, 47, 51, 54, 21, 59, 34],
       [89, 70, 43, 41, 98, 24, 69],
       [34, 72, 69, 87, 93, 53, 42],
       [49, 64, 96, 21, 57, 25, 57],
       [56, 87, 94, 66, 84, 53, 73]], dtype=int32)

In [4]:
arr.size

42

In [5]:
m=[2,43,24,2,34]
m

[2, 43, 24, 2, 34]

In [9]:
n=[i*i for i in m]
n

[4, 1849, 576, 4, 1156]

In [10]:
b=(i*i for i in m)
b

<generator object <genexpr> at 0x000001CBF4814380>

In [11]:
b=tuple(x+5 for x in m)
b

(7, 48, 29, 7, 39)

In [12]:
k=[87,8,89,685,86]
k

[87, 8, 89, 685, 86]

In [13]:
l=tuple(x+5 for x in k)
l

(92, 13, 94, 690, 91)

In [2]:
import numpy as np

In [5]:
a=np.random.randint(30,50,15)

In [6]:
a

array([42, 41, 36, 33, 44, 44, 44, 40, 47, 35, 44, 36, 38, 39, 35],
      dtype=int32)

In [13]:
np.random.seed(94)
b=np.random.randint(45,78,(7,8))
b


array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]], dtype=int32)

In [20]:
b[1:][1:7]

array([[71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]], dtype=int32)

In [25]:
b[-6::1,-7:-1:1]

array([[59, 55, 77, 69, 69, 48],
       [56, 51, 58, 59, 47, 68],
       [45, 52, 74, 65, 53, 60],
       [72, 46, 69, 65, 75, 75],
       [67, 53, 77, 60, 67, 67],
       [54, 74, 69, 54, 64, 52]], dtype=int32)

In [27]:
b[1:6,0::2]

array([[61, 55, 69, 48],
       [71, 51, 59, 68],
       [46, 52, 65, 60],
       [64, 46, 65, 75],
       [75, 53, 60, 67]], dtype=int32)